name: PHPUnit

on:
  pull_request:
  merge_group:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  file-diff:
    runs-on: ubuntu-latest
    name: File Diff
    outputs:
      php_diff: ${{ steps.php_diff_files.outputs.diff }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Check PHP files diff
        id: php_diff_files
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.php
            composer.+(json|lock)
            .github/**/*.yml

  test:
    runs-on: ubuntu-latest
    needs: [ 'file-diff' ]
    if: ${{ github.event.pull_request.title == null || needs.file-diff.outputs.php_diff }}
    strategy:
      fail-fast: false
      matrix:
        php_versions: [ '8.1', '8.3' ]
    name: PHPUnit - PHP version ${{ matrix.php_versions }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

#    steps:
#      - name: Checkout source code
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: ${{ matrix.php_versions }}
#          coverage: xdebug
#      - name: Run Tests without Coverage
#        if: ${{ ! matrix.php_versions >= 8.1  }}
#        run: |
#          composer remove --dev thor-juhasz/phpunit-coverage-check --ignore-platform-reqs
#          composer update --no-interaction
#          composer run test
#      - name: Run Tests with Coverage
#        if: ${{ matrix.php_versions >= 8.1 }}
#        run: |
#          composer update --no-interaction
#          composer run phpunit-coverage

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: xdebug

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit --coverage-text

  test-result:
    needs: test
    if: ${{ always() }} # Will be run even if 'test' matrix will be skipped
    runs-on: ubuntu-20.04
    name: PHPUnit - Test Results
    steps:
      - name: Test status
        run: echo "Test status is - ${{ needs.test.result }}"
      - name: Check test matrix status
        if: ${{ needs.test.result != 'success' && needs.test.result != 'skipped' }}
        run: exit 1
